export const APPOINTMENT_STATUS = {
  PENDING: "pending",
  APPROVED: "approved",
  ARRIVED: "arrived",
  CONSULTATION_STARTED: "consultation-started",
  CONSULTATION_COMPLETED: "consultation-completed",
  FOLLOW_UP: "follow-up",
  CANCELLED: "cancelled",
  REJECTED: "rejected",
  RESCHEDULED: "rescheduled",
  NO_SHOW: "no-show",
  IN_PROGRESS: "in-progress",
  COMPLETED: "completed"
};

export const lifecycleTransitions = {
  [APPOINTMENT_STATUS.PENDING]: [
    APPOINTMENT_STATUS.APPROVED,
    APPOINTMENT_STATUS.REJECTED,
    APPOINTMENT_STATUS.CANCELLED
  ],
  [APPOINTMENT_STATUS.APPROVED]: [
    APPOINTMENT_STATUS.ARRIVED,
    APPOINTMENT_STATUS.CANCELLED,
    APPOINTMENT_STATUS.REJECTED
  ],
  [APPOINTMENT_STATUS.ARRIVED]: [
    APPOINTMENT_STATUS.CONSULTATION_STARTED,
    APPOINTMENT_STATUS.CANCELLED
  ],
  [APPOINTMENT_STATUS.CONSULTATION_STARTED]: [
    APPOINTMENT_STATUS.CONSULTATION_COMPLETED
  ],
  [APPOINTMENT_STATUS.CONSULTATION_COMPLETED]: [APPOINTMENT_STATUS.FOLLOW_UP],
  [APPOINTMENT_STATUS.FOLLOW_UP]: [],
  [APPOINTMENT_STATUS.RESCHEDULED]: [APPOINTMENT_STATUS.APPROVED],
  [APPOINTMENT_STATUS.IN_PROGRESS]: [APPOINTMENT_STATUS.COMPLETED],
  [APPOINTMENT_STATUS.COMPLETED]: []
};

export const canTransitionStatus = (from, to) => {
  if (from === to) return true;
  const allowed = lifecycleTransitions[from] || [];
  return allowed.includes(to);
};

export const isFinalizedStatus = (status) => {
  return [
    APPOINTMENT_STATUS.CANCELLED,
    APPOINTMENT_STATUS.REJECTED,
    APPOINTMENT_STATUS.NO_SHOW,
    APPOINTMENT_STATUS.CONSULTATION_COMPLETED,
    APPOINTMENT_STATUS.COMPLETED
  ].includes(status);
};
